# Generated by Django 3.2.3 on 2021-05-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='sell_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(default='', max_length=50)),
                ('branch', models.CharField(choices=[('E&TC Engineer', 'E&TC Engineer'), ('Information Technology', 'Information Technology'), ('Mechanical Engineer', 'Mechanical Engineer'), ('Civil Engineer', 'Civil Engineer'), ('Computer Engineer', 'Computer Engineer')], default='', max_length=50)),
                ('year', models.CharField(choices=[('BE', 'BE'), ('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE')], default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('bookset_image', models.ImageField(blank=True, null=True, upload_to='sell/Uploaded_Images')),
                ('book_name_a', models.CharField(blank=True, default='', max_length=50)),
                ('book_type_a', models.CharField(blank=True, choices=[('Second-Hand', 'Second-Hand'), ('Original', 'Original'), ('Photocopy', 'Photocopy')], default='', max_length=50)),
                ('price_a', models.IntegerField(blank=True, default=0)),
                ('image_a', models.ImageField(blank=True, null=True, upload_to='sell/Uploaded_Images')),
                ('book_name_b', models.CharField(blank=True, default='', max_length=50)),
                ('book_type_b', models.CharField(blank=True, choices=[('Second-Hand', 'Second-Hand'), ('Original', 'Original'), ('Photocopy', 'Photocopy')], default='', max_length=50)),
                ('price_b', models.IntegerField(blank=True, default=0)),
                ('image_b', models.ImageField(blank=True, null=True, upload_to='sell/Uploaded_Images')),
                ('book_name_c', models.CharField(blank=True, default='', max_length=50)),
                ('book_type_c', models.CharField(blank=True, choices=[('Second-Hand', 'Second-Hand'), ('Original', 'Original'), ('Photocopy', 'Photocopy')], default='', max_length=50)),
                ('price_c', models.IntegerField(blank=True, default=0)),
                ('image_c', models.ImageField(blank=True, null=True, upload_to='sell/Uploaded_Images')),
                ('book_name_d', models.CharField(blank=True, default='', max_length=50)),
                ('book_type_d', models.CharField(blank=True, choices=[('Second-Hand', 'Second-Hand'), ('Original', 'Original'), ('Photocopy', 'Photocopy')], default='', max_length=50)),
                ('price_d', models.IntegerField(blank=True, default=0)),
                ('image_d', models.ImageField(blank=True, null=True, upload_to='sell/Uploaded_Images')),
                ('book_name_e', models.CharField(blank=True, default='', max_length=50)),
                ('book_type_e', models.CharField(blank=True, choices=[('Second-Hand', 'Second-Hand'), ('Original', 'Original'), ('Photocopy', 'Photocopy')], default='', max_length=50)),
                ('price_e', models.IntegerField(blank=True, default=0)),
                ('image_e', models.ImageField(blank=True, null=True, upload_to='sell/Uploaded_Images')),
                ('book_name_f', models.CharField(blank=True, default='', max_length=50)),
                ('book_type_f', models.CharField(blank=True, choices=[('Second-Hand', 'Second-Hand'), ('Original', 'Original'), ('Photocopy', 'Photocopy')], default='', max_length=50)),
                ('price_f', models.IntegerField(blank=True, default=0)),
                ('image_f', models.ImageField(blank=True, null=True, upload_to='sell/Uploaded_Images')),
                ('description', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
